name:                JsonPP
version:             0.1.0.0
github:              "abodhare/JsonPP"
license:             BSD3
author:              "abodhare"
maintainer:          "abodhare1234+1@gmail.com"
copyright:           "2020 abodhare"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/JsonPP#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  JsonPP-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JsonPP

tests:
  JsonPP-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - JsonPP
    - hspec
    - hspec-discover
    - QuickCheck
